# k8s/service-nodeport.yaml（試験用）
apiVersion: v1
kind: Service
metadata:
  name: service1-nodeport
  namespace: service1-lab
spec:
  type: LoadBalancer
  selector:
    app: service1
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30080
